# Background

According to the United Nations Conference on Trade and Development (UNCTAD), around 80% of international trade in goods by volume is done by the sea. This global cooperation is without cost, as the fuel burned by trade ships to transport goods adds a nontrivial amount of greenhouse gas to the atmosphere \cite{STALKER2021}. It has been estimated that around 3% of global carbon dioxide emissions, 8% of global sulfur dioxide emissions, and 15% of global nitrogen oxide emissions come from the combustion of fuel in ships [@IMO2020}] \cite{SARBANHA2023}. The objective to lower greenhouse gas emissions has been laid out by the International Maritime Organization (IMO) such that emissions will be reduced by at least 40% by 2030 and 50-70% by 2050 with respect to the 2008 levels \cite{WANG2025104689}. Cleaner fuels such as bio-LNG, bio-methanol, and ng-ammonia are already being tested and adopted \cite{WANG2025104689}. However, fossil fuels are still widely used, and the proportion of global emissions maritime activity is accountable for continues to climb \cite{catal12020138} \cite{IMO2020}. The impact of carbon emissions in the atmosphere and ocean are already well documented. It is known that nitrogen oxide emissions are a precursor to ozone and that sulfur oxide emissions have a detrimental effect on human health \cite{EYRING20104735}. However, the effect of nitrogen oxides on the open ocean is less readily available. 

Plankton are small aquatic organisms, all of which have little to no swimming ability and move with the ocean currents \cite{BRIERLEY2017}. One of the trophic modes of plankton is phytoplankton, composed of photosynthetic plants and bacteria. Phytoplankton play an important role in the ocean ecosystem, contributing to about half of the world's primary production, i.e. converting inorganic compounds into organic compounds via a process such as photosynthesis \cite{PASCAL2021}. This photosynthetic activity also has a great effect on carbon dioxide levels in the atmosphere. It has been estimated that around 40% of anthropogenic carbon dioxide dissolves into the ocean, and a single type of phytoplankton, diatom, is responsible for fixing a quarter of that carbon dioxide via photosynthesis each year \cite{BRIERLEY2017}. Phytoplankton are highly sensitive to changes in their environment, such as temperature, nutrient availability, acidity, and even light intensity \cite{BRIERLEY2017}. This makes phytoplankton a good proxy for measuring changes to the ocean environment.

One of these nutrients utilized by phytoplankton is nitrate (a nitrogen oxide species). Elevated concentrations of nitrate in bodies of water can cause increases in the phytoplankton population \cite{HARRISON1988} \cite{DOMINGUES2011}. Extreme cases of planktonic growth cause a phenomenon called algal blooms. The vast amount of plankton from algal blooms remove all the oxygen from the water, creating what are called hypoxic zones, which suffocate all marine life in the area and damage the ecosystem. The source of this nitrogen has been shown to be from fertilizer on many occasions \cite{deutsch2006assessing} \cite{puckett1995identifying} \cite{zhang2014tracing}. Whether or not the nitrogen oxide emissions from ship exhaust have any effect on nitrate and plankton levels in the open waters of the ocean has not yet been documented. 
