project:
  type: manuscript
  output-dir: .          
  resources:
    - "_*.qmd"

manuscript:
  article: capstone.qmd

format: 
  html:
    output-file: index    
    theme:
      light: lightly
      dark: darkly
bibliography: references.bib
